# -*- coding: utf-8 -*-
"""Slicer placeholder substitution for uploaded G-code.

Happy Hare ships a Moonraker component (``components/mmu_server.py``) that
rewrites placeholders in a sliced file at upload time so ``MMU_START_SETUP`` can
hand the slicer's tool colours, materials, temperatures and purge volumes to the
MMU. That component never runs on an OctoPrint-only machine, so this is a port of
its parsing, working on the file OctoPrint is about to store.

Ported from Happy Hare (moggieuk/Happy-Hare, ``components/mmu_server.py``, GPLv3);
the regexes and the fingerprint are kept identical so a file processed here is
indistinguishable from one Moonraker processed.

Stdlib only - no OctoPrint imports - so it can be unit tested directly.
"""

from __future__ import absolute_import, unicode_literals

import io
import re

FINGERPRINT = "; processed by HappyHare"

SUPPORTED_SLICERS = ("PrusaSlicer", "SuperSlicer", "OrcaSlicer", "BambuStudio")

SLICER_REGEX = re.compile(r"^;.*generated by ([a-z]*) .*$|^; (BambuStudio) .*$", re.IGNORECASE)
ORCA_VERSION_REGEX = re.compile(r"^;\s*generated by OrcaSlicer\s+(\d+(?:\.\d+){0,3})", re.IGNORECASE)
TOOL_DISCOVERY_REGEX = re.compile(
    r"((^MMU_CHANGE_TOOL(_STANDALONE)? .*?TOOL=)|(^T))(?P<tool>\d{1,2})", re.IGNORECASE)

COLORS_REGEX = {
    "PrusaSlicer": r"^;\s*(?:extruder|filament)_colour\s*=\s*(#.*;*.*)$",
    "SuperSlicer": r"^;\s*(?:extruder|filament)_colour\s*=\s*(#.*;*.*)$",
    "OrcaSlicer": r"^;\s*filament_colour\s*=\s*(#.*;*.*)$",
    "BambuStudio": r"^;\s*filament_colour\s*=\s*(#.*;*.*)$",
}
TEMPS_REGEX = re.compile(r"^;\s*(nozzle_)?temperature\s*=\s*(.*)$", re.IGNORECASE)
MATERIALS_REGEX = re.compile(r"^;\s*filament_type\s*=\s*(.*)$", re.IGNORECASE)
PURGE_VOLUMES_REGEX = re.compile(
    r"^;\s*(flush_volumes_matrix|wiping_volumes_matrix)\s*=\s*(.*)$", re.IGNORECASE)
FLUSH_MULTIPLIER_REGEX = re.compile(r"^;\s*flush_multiplier\s*=\s*(.*)$", re.IGNORECASE)
FILAMENT_NAMES_REGEX = re.compile(r"^;\s*(filament_settings_id)\s*=\s*(.*)$", re.IGNORECASE)

PLACEHOLDERS = {
    "tools": "!referenced_tools!",
    "total_toolchanges": "!total_toolchanges!",
    "colors": "!colors!",
    "temps": "!temperatures!",
    "materials": "!materials!",
    "purge_volumes": "!purge_volumes!",
    "filament_names": "!filament_names!",
}


def _version_tuple(text, parts=3):
    match = re.match(r"^\s*(\d+(?:\.\d+)*)", text or "")
    if not match:
        return None
    numbers = []
    for chunk in match.group(1).split(".")[:parts]:
        try:
            numbers.append(int(chunk))
        except ValueError:
            numbers.append(0)
    while len(numbers) < parts:
        numbers.append(0)
    return tuple(numbers)


def _format_volume(value):
    value = round(float(value), 1)
    return ("%.1f" % value).rstrip("0").rstrip(".")


def already_processed(line):
    return (line or "").lstrip().lower().startswith(FINGERPRINT.lower())


def scan(stream):
    """Read a sliced file and pull out everything the placeholders need.

    ``stream`` yields text lines. Returns a dict of findings; ``has_placeholders``
    says whether the file asks for substitution at all.
    """
    found = {
        "slicer": None,
        "orca_version": None,
        "tools": [],
        "total_toolchanges": 0,
        "colors": [],
        "temps": [],
        "materials": [],
        "purge_volumes": [],
        "filament_names": [],
        "flush_multiplier": 1.0,
        "has_placeholders": False,
        "placeholders": set(),
    }

    tools_used = set()
    colors = []
    seen = {"colors": False, "temps": False, "materials": False,
            "purge": False, "names": False, "multiplier": False}
    colors_regex = None

    for line in stream:
        if line.startswith(";"):
            if found["slicer"] is None:
                match = SLICER_REGEX.match(line)
                if match:
                    name = match.group(1) or match.group(2)
                    # normalise to the exact spelling used in COLORS_REGEX
                    for slicer in SUPPORTED_SLICERS:
                        if name and name.lower() == slicer.lower():
                            found["slicer"] = slicer
                            colors_regex = re.compile(COLORS_REGEX[slicer], re.IGNORECASE)
                            break
            if found["orca_version"] is None:
                match = ORCA_VERSION_REGEX.match(line)
                if match:
                    found["orca_version"] = _version_tuple(match.group(1))

        for key, token in PLACEHOLDERS.items():
            if token in line:
                found["placeholders"].add(key)
                found["has_placeholders"] = True

        match = TOOL_DISCOVERY_REGEX.match(line)
        if match:
            tools_used.add(int(match.group("tool")))
            found["total_toolchanges"] += 1

        if colors_regex is not None and not seen["colors"]:
            match = colors_regex.match(line)
            if match:
                csv = [color.strip().lstrip("#") for color in match.group(1).split(";")]
                if not colors:
                    colors = csv
                else:
                    colors = [new if old == "" else old for old, new in zip(colors, csv)]
                seen["colors"] = all(len(color) > 0 for color in colors)

        if not seen["temps"]:
            match = TEMPS_REGEX.match(line)
            if match:
                found["temps"] = [value.strip() for value in re.split(r"[;,]", match.group(2).strip())]
                seen["temps"] = True

        if not seen["materials"]:
            match = MATERIALS_REGEX.match(line)
            if match:
                found["materials"] = [value.strip() for value in match.group(1).strip().split(";")]
                seen["materials"] = True

        if not seen["multiplier"]:
            match = FLUSH_MULTIPLIER_REGEX.match(line)
            if match:
                try:
                    found["flush_multiplier"] = float(match.group(1).strip())
                except ValueError:
                    found["flush_multiplier"] = 1.0
                seen["multiplier"] = True

        if not seen["purge"]:
            match = PURGE_VOLUMES_REGEX.match(line)
            if match:
                # Stored raw and scaled once the whole file has been read: the
                # multiplier can appear either side of the matrix, and scaling
                # inline would silently use 1.0 when it comes later.
                found["purge_volumes"] = [value.strip()
                                          for value in match.group(2).strip().split(",")]
                seen["purge"] = True

        if not seen["names"]:
            match = FILAMENT_NAMES_REGEX.match(line)
            if match:
                found["filament_names"] = [value.strip()
                                           for value in re.split(r"[,;]", match.group(2).strip())]
                seen["names"] = True

    found["colors"] = colors
    found["tools"] = sorted(tools_used)
    found["purge_volumes"] = _scale_purge_volumes(found)
    return found


def _scale_purge_volumes(found):
    """Apply flush_multiplier, except where the slicer already did.

    OrcaSlicer 2.3.2 and later bake the multiplier into flush_volumes_matrix.
    """
    volumes = found["purge_volumes"]
    multiplier = found["flush_multiplier"]
    if not volumes or multiplier == 1.0:
        return volumes
    if found["slicer"] == "OrcaSlicer" and found["orca_version"] is not None             and found["orca_version"] >= (2, 3, 2):
        return volumes
    scaled = []
    for value in volumes:
        try:
            scaled.append(_format_volume(float(value) * multiplier))
        except ValueError:
            scaled.append(value)
    return scaled


def substitutions(found):
    """Build the placeholder -> replacement text map."""
    tools = ",".join(str(tool) for tool in found["tools"]) if found["tools"] else "0"
    return {
        PLACEHOLDERS["tools"]: tools,
        PLACEHOLDERS["total_toolchanges"]: str(found["total_toolchanges"]),
        PLACEHOLDERS["colors"]: ",".join(found["colors"]),
        PLACEHOLDERS["temps"]: ",".join(found["temps"]),
        PLACEHOLDERS["materials"]: ",".join(found["materials"]),
        PLACEHOLDERS["purge_volumes"]: ",".join(found["purge_volumes"]),
        PLACEHOLDERS["filament_names"]: ",".join(found["filament_names"]),
    }


def process_file(source_path, target_path):
    """Substitute placeholders from ``source_path`` into ``target_path``.

    Returns ``(changed, metadata)``. ``changed`` is False when the file needs no
    work (already processed, unsupported slicer, or no placeholders), in which
    case ``target_path`` is not written.
    """
    with io.open(source_path, "r", encoding="utf-8", errors="replace") as handle:
        first_line = handle.readline()
        if already_processed(first_line):
            return False, {"skipped": "already processed"}
        handle.seek(0)
        found = scan(handle)

    metadata = {
        "slicer": found["slicer"],
        "tools": found["tools"],
        "total_toolchanges": found["total_toolchanges"],
        "colors": found["colors"],
        "materials": found["materials"],
        "temps": found["temps"],
        "filament_names": found["filament_names"],
        "purge_volumes": found["purge_volumes"],
        "processed": False,
    }

    if found["slicer"] not in SUPPORTED_SLICERS:
        metadata["skipped"] = "unsupported slicer"
        return False, metadata
    if not found["has_placeholders"]:
        metadata["skipped"] = "no placeholders"
        return False, metadata

    replacements = substitutions(found)
    with io.open(source_path, "r", encoding="utf-8", errors="replace") as src, \
            io.open(target_path, "w", encoding="utf-8", newline="") as dst:
        dst.write(FINGERPRINT + "\n")
        for line in src:
            if not line.startswith(";"):
                for token, value in replacements.items():
                    if token in line:
                        line = line.replace(token, value)
            dst.write(line)

    metadata["processed"] = True
    return True, metadata
